### ISSUE TITLE
check for new message

### ISSUE THREAD

**Issue by predic8** [predic8/activemq-nagios-plugin#10]
Somebody need to know if there is a new message in a queue like the DLQ for instance. 

Maybe we need to store somewhere a counter for a queue.

**Comment by predic8** [comment]
Store:
in ~/.cache/activemq-nagios-plugin 

for each message the messageId

ID:Thomass-MacBook-Pro.local-55075-1448011812464-3:1:1:1:1

size for each monitored queue
Parameter: queuename

If queue

**Comment by r41d** [comment]
implemented by remembering the amount of messages
