### ISSUE TITLE
check subscriber should test for offline

### ISSUE THREAD

**Issue by predic8** [predic8/activemq-nagios-plugin#3]
The check:

./check_activemq.py -u admin -p admin subscriber --clientId Sub3 --topic preise
ACTIVEMQSUBSCRIBER OK - Client Sub3 is subscriber of Topic preise

tests if Sub is a subscriber. But it should check is Sub is currently an active subsciber. 

If Sub3 is not an active subscriber => WARN
If Sub3 is not an subscriber at all => CRITICAL

![bildschirmfoto 2015-06-09 um 12 02 25](https://cloud.githubusercontent.com/assets/1932856/8055365/71ec67fa-0e9f-11e5-86b5-31615a080335.png)

**Comment by r41d** [comment]
Implemented with 3c7418e.
For this to work, the script needed some restructuring, but this feature commit also includes better debug output and error handling.
